FROM runpod/kasm-docker:cuda11

RUN sudo mkdir -p /home/ht/training
RUN sudo chown -R kasm-user /home/ht/training
WORKDIR /home/ht/training

RUN sudo apt-get update

# To send files via zip later on
RUN sudo apt-get -y install zip

# Install Python 3.11
RUN sudo apt-get -y install python3.11
RUN sudo apt-get -y install python3.11-venv

# Dependencies for QT (which LoRA_Easy_Training_Scripts uses)
RUN sudo apt-get -y install build-essential
RUN sudo apt-get -y install libx11-xcb-dev libglu1-mesa-dev
RUN sudo apt-get -y install libxcb-cursor0

# Checkout and install LoRA_Easy_Training_Scripts
RUN git clone https://github.com/derrian-distro/LoRA_Easy_Training_Scripts
WORKDIR /home/ht/training/LoRA_Easy_Training_Scripts
RUN sh -c '/bin/echo -e "y" | python3.11 install.py'

# Start training UI on pod startup
COPY ./run-trainer.sh /home/ht/training
COPY ./select-checkpoint.sh /home/ht/training
COPY ./startup-run-trainer.sh /dockerstartup/custom_startup.sh